### ISSUE TITLE
Singles Best Search Algorithm

### ISSUE THREAD

**Issue by Mdong9** [The-Pancake/Housing-2.0#16]
**Task:**
Create an algorithm that tries to find a room for an individual or roommate with similar preferences

**Comment by jack-sherick** [comment]
After a bit of thinking on how to do the actual algorthim I think I've come up with a solid baseline first plan that can be expounded upon later in documentation and proper detail. For now, what I'm writing is similar to the idea that was presented in the beginning: it's two seperate search functions, a "perfect" fit and an ideal fit. What is does it looks for the "peferct" match, a single that is paired with someone with a very high similarity in whatever we take in the front end and in one of there preferred dorms (if there is one). While it looks for this "perfect" fit, it takes in decent fits and stores them in an array. That array is used for the ideal fit function, where it looks at each potential room and weights those (so how high that room was on their preferred list, how similar any of the occupants if a room is occupied, etc.), and takes the highest weighted room and uses that to get the ideal fit. This way we don't have to manually choose between ideal and best fit, it does both at the same time, at max is looks through the rooms twice, so the runtime is good, and it does a good job at finding the best possible solution for any given person.

I have a lot of things I need to work on, and some conceptual things that need to be done together (how to weight things [Jamarri had the great point of people being able to rank how they want to weight things, and this way it can be used almost all the time], storage, allocation, movement, etc.), but for a beginning idea I think it's pretty good. I'm going to work over the weekend to get a very basic version of this running, but I'm really busy I doubt I'll get close to finishing.

If there are any ideas on what else we can do, or whatever let me know. I imagine that I'll be able to work with Daniel externally, and we are the only two working on singles for the moment, but I think this'll work, even in the long term.
