### ISSUE TITLE
Create wireframe for contact us page

### ISSUE THREAD

**Issue by liuj-42** [The-Pancake/Housing-2.0#52]
todo:
- [ ] Contact Form
- [x] Displays housing administrator contact information

**Comment by Aditya-Dhodapkar** [comment]
What exactly is the contact form here?

**Comment by liuj-42** [comment]
Looks something like this 
![image](https://github.com/The-Pancake/Housing-2.0/assets/65922029/b11fa52c-5454-458c-9b71-f3f1fb40f9c9)

**Comment by liuj-42** [comment]
Closing because the current wireframe for the contact page is already good
