### ISSUE TITLE
Ideas for different campus.json data structure

### ISSUE THREAD

**Issue by Mdong9** [The-Pancake/Housing-2.0#6]
Different ideas to format the campus data for most efficient time for different algorithms to access

**Comment by jack-sherick** [comment]
I've been trying to work a good bit, and for the structure a 1D array seems pretty simple. If a student wants a specific house we can jump to that point in the array, and for iterating over it, we don't need to access anything in two dimensions, making the movement and reallocation of students faster, making the case where a specific house is wanted the speed is the same, and all other cases faster (I think, don't quote me). A 1D array also just seems hella easy to implement.

**Comment by Mdong9** [comment]
With the current campus.json data structure we have, after discussion today (2/28/2023), We have concluded that as visually intuitive as having a "floors" level in our data structure is. In our code and overall use it would only create unnecessary confusion as well as not provide any extra help in what our room finding algorithm does utilizing information about rooms as well as dorm halls.
